defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    sampler:
      seed: 42
    direction: minimize
    study_name: grp-64-h-optim-continuous
    storage: null
    n_trials: 40
    n_jobs: 2
    params:
      batch_size: choice(256, 512)
      n_embd: choice(256, 512)
  
batch_size: 512 # how many independent sequences will we process in parallel?
block_size: 32 # what is the maximum context length for predictions?
vocab_size: 32
n_patches: 8
max_iters: 50000
eval_interval: 100
learning_rate: 5e-5
eval_iters: 200
n_embd: 512
device: "cpu"
testing: false
# ------------

r_seed: 1337
n_head: 16
n_blocks: 4
dropout: 0.2
action_bins: 10
action_dim: 6

## Model hyperparameters
image_shape: [64, 64, 3]
dataset: gberseth/mini-bridge-mini64pix
trim: 1000000

# if true, simulate a failure by raising an exception
error: false